// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ASPNETCoreWebApi6.Models
{
    public partial class ContosouniversityContext : DbContext
    {
        //public override int SaveChanges()
        //{
        //    return base.SaveChanges();
        //}
        
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {

            //modelBuilder.Entity<VwDepartmentCourseCount>(entity =>
            //{
            //    entity.HasNoKey();

            //    entity.ToSqlQuery("SELECT * FROM vwDepartmentCourseCount");

            //    entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");

            //    entity.Property(e => e.Name).HasMaxLength(50);
            //});

        }
    }
}